---
title: "hist_qq_boot_and_scatter_boot"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hist_qq_boot_and_scatter_boot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(semboottools)
library(lavaan)
```

## Example
```{r}
library(lavaan)

# Simulate data
set.seed(1234)
n <- 200
x <- runif(n) - 0.5
m <- 0.4 * x + rnorm(n)
y <- 0.3 * m + rnorm(n)
dat <- data.frame(x, m, y)

# Specify model
model <- '
  m ~ a * x
  y ~ b * m + cp * x
  ab := a * b
'

# Fit model
fit0  <- sem(model, data = dat, fixed.x = FALSE)
```

### Basic usage: default settings
```{r}
fit1 <- store_boot(fit0,R = 5000,iseed = 2345)
hist_qq_boot(fit1, param = "ab", standardized = FALSE)
scatter_boot(fit1, c("ab", "a", "b"), standardized = FALSE)
```

```{r}
hist_qq_boot(fit1, param = "ab", standardized = TRUE)
scatter_boot(fit1, c("a", "b", "ab"), standardized = TRUE)
```

